name: Auto Reply to Giscus Comments

# Trigger on new discussion comments
on:
  discussion_comment:
    types: [created]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Reply to Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Sujithts12/Sujith_siddarth_portfolio
          discussion-number: ${{ github.event.discussion.number }}
          body: "Thank you for your feedbackğŸ™. Your comments are highly appreciated and help me continuously improve my work."
